### ISSUE TITLE
Handshake negotiation

### ISSUE THREAD

**Issue by madari** [LearnBoost/socket.io-spec#2]
The spec states that "Once the handshake request-response cycle is complete (and it ended with success), a new connection is opened by the transport that was negotiated", but the spec
has nothing on how the transport is actually negotiated

**Comment by rauchg** [comment]
Sorry I actually removed the last transport negotiation technique (it would basically say can I connect with websocket, and if not, a response code and the body would be a comma-separated list of supported transports)

I'm going to change it to the client sending all the transports it might potentially try, and the server responding with an error if _none_ are supported, or the intersection of supported transports as part of the handshake response if successful.

**Comment by madari** [comment]
Ok - that sounds reasonable :)
