### ISSUE TITLE
Is this repository actively maintained?

### ISSUE THREAD

**Issue by WillDignazio** [LearnBoost/socket.io-spec#28]
This spec shows up for most folk working with socket.io as a reference. There seems to be several people with pull requests, going _years_ back. They also don't seem to be getting commentary on why their requests aren't getting merged in.

I would appreciate it if the maintainers of this repository did some maintenance and updated the documentation to reflect the current standard, or fix up any erroneous material in this spec.

**Comment by rauchg** [comment]
This is the new one:
https://github.com/automattic/socket.io-protocol

**Comment by rauchg** [comment]
I updated the README to point to the up-to-date docs. I apologize for the confusion. Thanks for bringing this to our attention!

**Comment by WillDignazio** [comment]
Thanks for the quick response!
